spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  # \u6570\u636E\u5E93\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    # \u914D\u7F6EDruid\u8FDE\u63A5\u6C60
    type: com.alibaba.druid.pool.DruidDataSource
  # \u914D\u7F6Esession\u5B58\u50A8\u65B9\u5F0F\uFF0C\u6682\u65F6\u5173\u6389\u8BE5\u529F\u80FD
  session:
    store-type: none
  server:
    port: 8080
  redis:
    host: 127.0.0.1
    port: 6379
    password: jtzsw_redis
    timeout: 6000

# \u9996\u5148\u5C06\u6743\u9650\u9A8C\u8BC1\u5173\u95ED
#security:
#  basic:
#    enabled: false


# 配置图形验证码
com:
  hao:
    security:
      code:
        image:
          length: 4
          url: /user,/user/*
        # 配置短信验证码
        sms:
          length: 6
          url: /user,/user/*
      social:
        qq:
          app-id: 101547587
          app-secret: c3329b622cf39480774fe483d1d1a546
        filterProcessesUrl: /authentication